# Generated by Django 3.0 on 2019-12-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20191214_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bytes',
            field=models.BinaryField(max_length=10),
        ),
    ]
