# Generated by Django 3.0 on 2019-12-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_auto_20191214_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bytes',
            field=models.BinaryField(default=b'hello', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='clustered_images/', upload_to='clustered_images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
