# Generated by Django 3.0 on 2019-12-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_auto_20191215_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
